url: https://markusaj13.github.io
baseurl: ""

# Site settings
title: Markus Sida
email: markus96johansson@gmail.com
description: "Markus Sida"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Bounce96
  - title: github
    url: https://github.com/Markusaj13/

# Postal address (add as many lines as necessary)
address:
  - line: Stora Björnens gata
  - line: Haninge, Sweden

# Build settings
markdown: kramdown
permalink: pretty